# Generated by Django 4.2.7 on 2023-11-14 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_app', '0003_alter_userprofile_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100)),
                ('site_url', models.URLField()),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vpn_app.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='UserSiteTraffic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('data_sent', models.FloatField(default=0)),
                ('data_received', models.FloatField(default=0)),
                ('user_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vpn_app.usersite')),
            ],
        ),
    ]
